import { state } from "./01-state";
import { skillIcon } from "./12-boss-images";
import { renderRotation } from "./25-rotation";

/* ---------- die Symbole ----------
   313 Symbole: 275 aus dem Feed getSkillSets von questlog.gg, verkleinert
   von 200x200 (einige 300x300) auf 64x64, und 38 aus eigenen Vorlagen
   ("boro:..."), weiter in 32x32. Deine Rotation zeigt die Symbole
   mit 32 bis 40 Punkten, bei 175 % Windows-Skalierung also 56 bis 70
   Pixel; 32x32 wurde dort matschig (Entscheidung 27.09.). Die questlog-Bilder
   wiegen jetzt 658 kB als Webp (Qualitaet 0,85), 878 kB als Base64. Die
   Vorlagen bleiben klein, bis es sie wieder in voller Groesse gibt.

   Zwei Tabellen und nicht eine: 616 Namen zeigen auf 313 Bilder. Derselbe
   Skill heisst auf Deutsch anders und traegt dasselbe Symbol, und
   mehrere Spezialisierungen teilen sich das Symbol ihrer Familie. Das
   Bild einmal statt mehrfach zu halten spart nicht die Haelfte, sondern
   das Vielfache.

   Enthalten sind die 210 Skillsets UND ihre 110 Spezialisierungen. Ohne
   die zweiten fehlte in einem eigenen Kampf sechsmal das Symbol, darunter bei
   der Faehigkeit mit 80 % des Schadens.

   AUGE VON VENTIUS ist ein Sonderfall: questlog kennt den Namen nicht.
   Die App liest ihn selbst aus der Trefferform von "Entschlossener
   Scharfschuss" und benennt die Zeile um. Verknuepft ist deshalb das
   Symbol dieser Familie - dieselbe Lesart, die die Marke an der Zeile
   schon nennt ("Im Log steht Entschlossener Scharfschuss"). */
export { KERN_BILD, SKILL_ICON_BILD } from "../spielbilder";
export const SKILL_ICON_NAME: Record<string, string> = {
  "Falling Flower":"WM_Common_SKILL_009",
  "Fallende Blume":"WM_Common_SKILL_009",
  /* Zeigen auf das Bild von Unshakable Stance, beide auf
     Angabe des Spielers. Bei Iron Mountain Blow nachgemessen: Abstand 10,5 von 255
     zwischen seinem Bild und S_WP_GT_CounterMove, fremde Symbole
     liegen bei 52 bis 58. Evasive Maneuver kennt questlog gar nicht -
     kein Skillset, kein Datenbankeintrag -, hier gibt es also nichts
     nachzumessen, nur seine Auskunft. */
  "Iron Mountain Blow":"S_WP_GT_CounterMove",
  "Evasive Maneuver":"S_WP_GT_CounterMove",
  "A Shot at Victory":"S_WP_SW_SH_S_DoubleChanceAttack_1",
  "Abgrundspalt":"S_WP_SP_StunAttack",
  "Abyssal Cleave":"S_WP_SP_StunAttack",
  "Adlersicht":"S_WP_CR_DistanceRangeAcc_AA",
  "Aegis Shield":"S_WP_SH_ArmorUp_AA",
  "Aegis-Schild":"S_WP_SH_ArmorUp_AA",
  "Ambidexterity":"S_WP_CR_OffHandMaxDmg_AA",
  "Amplification Veil":"S_WP_ORB_Active_Shield_SP_1",
  "Andacht und Leere":"S_WP_WA_GR_DayHealNightCurse_AA",
  "Ankle Strike":"S_WP_DA_LegAttack",
  "Annihilating Slash":"S_WP_SW_SH_S_WhirlwindSlash",
  "Annihilation Barrage Shot":"S_WP_CR_FuriousFire_SP",
  "Annihilation Blade":"S_WP_SW_SH_S_DoubleChanceAttack_SP",
  "Ansteigender Hieb":"S_WP_SP_CrossAttack",
  "Arrow Vortex":"S_WP_BO_TornadoShot",
  "Ascending Cleave":"S_WP_SP_StunAttack_SP",
  "Ascending Slash":"S_WP_SW2_UpperAttack",
  "Asceticism":"S_WP_ST_ManaRegenBuff_AA",
  "Askese":"S_WP_ST_ManaRegenBuff_AA",
  "Assassin's Instincts":"S_WP_DA_MeleeAccuracy_AA",
  "Assassin's Step":"S_AS_CO_Acceleration_AA",
  "Assassination Stance":"S_WP_DA_EvasionBuff",
  "Assassinenschritt":"S_AS_CO_Acceleration_AA",
  "Astral Overseer":"S_WP_ORB_Passive_OrbControl",
  "Astralaufseher":"S_WP_ORB_Passive_OrbControl",
  "Astralecho":"S_WP_ORB_Passive_SubProjectile",
  "Astralsprint":"S_WP_ORB_Active_Laser",
  "Astralzyklus":"S_WP_ORB_Passive_Circulation",
  "Attentatshaltung":"S_WP_DA_EvasionBuff",
  "Aufsteigender Hieb":"S_WP_SW2_UpperAttack",
  "Aufsteigender Spalt":"S_WP_SP_StunAttack_SP",
  "Aufwallen der Bosheit":"S_WP_SP_AttackedBuff",
  "Auge von Ventius":"boro:eye-of-ventius",
  "Ausl\u00f6schender Hieb":"S_WP_SW_SH_S_WhirlwindSlash",
  "Ausl\u00f6schender Sperrfeuerschuss":"S_WP_CR_FuriousFire_SP",
  "Ausl\u00f6schendes Schwert":"S_WP_SW_SH_S_DoubleChanceAttack_SP",
  "Ausschalten":"S_WP_GT_Disarm",
  "Barbarian's Dash":"S_WP_SW2_SkillMaster",
  "Barrier":"S_WP_ORB_DefenseActionSkill",
  "Barriere":"S_WP_ORB_DefenseActionSkill",
  "Bedrohungsschub":"S_WP_GT_AggroBuff",
  "Beeindruckende Form":"S_WP_SP_TwoHandWeapon",
  "Begin the Hunt":"S_WP_BO_AttackUpAura",
  "Beginne die Jagd":"S_WP_BO_AttackUpAura",
  "Beidh\u00e4ndigkeit":"S_WP_CR_OffHandMaxDmg_AA",
  "Belastbarer Geist":"S_WP_SH_BlockSucceedRewardMana_AA",
  "Ber\u00fchrung des Verfalls":"S_WP_WA_CurseArea_SP",
  "Beschuss":"S_WP_BO_MultiShot_AA",
  "Bet\u00e4ubender Schlag":"S_KN_SR_ShockStun_AA",
  "Beweglichkeitsschlag":"S_WP_GT_MoveAttack",
  "Blessed Barrier":"S_WP_WA_DefenseUp",
  "Blessing of Immortality":"S_WP_SW_S_MaxHealthUp_SP",
  "Blitz":"S_WP_BO_DoubleShot",
  "Blitzdurchdringung":"S_WP_DA_PoisonEnchant_SP",
  "Blitzpfeil":"S_WP_BO_Detection",
  "Blitzwelle":"S_WP_BO_Detection_SP",
  "Blitzwurf":"S_WP_DA_PoisonDagger_SP",
  "Block Blade":"S_WP_DA_CounterMove_ActionSkill_Guard_AA",
  "Blood Devotion":"S_WP_SW2_DamageReceive",
  "Bloodleech Aura":"S_WP_SP_BloodAura",
  "Bloodlust":"S_WP_ContinuousAttackBonus",
  "Bloody Claws":"S_WP_GT_EclipseOfBlood_Off",
  "Blutdurst":"S_WP_ContinuousAttackBonus",
  "Blutige Hingabe":"S_WP_SW2_DamageReceive",
  "Blutige Krallen":"S_WP_GT_EclipseOfBlood_Off",
  "Blutsaugeraura":"S_WP_SP_BloodAura",
  "Brandnebelschleier":"S_WP_ST_S_AoeTeleport_SP",
  "Breakthrough":"S_WP_GT_BattleSense",
  "Brechendes Parieren":"S_WP_CR_DefenseAction_Evasion_AA",
  "Brutal Arrow":"S_WP_BO_DropShot",
  "Brutal Fury":"S_WP_SP_RapidThrust_SP_1",
  "Brutal Incision":"S_WP_DA_DeadlyStrike_AA",
  "Brutaler Einschnitt":"S_WP_DA_DeadlyStrike_AA",
  "Brutaler Pfeil":"S_WP_BO_DropShot",
  "Brutaler Zorn":"S_WP_SP_RapidThrust_SP_1",
  "Burning Smokescreen":"S_WP_ST_S_AoeTeleport_SP",
  "Camouflage Cloak":"S_AS_SR_Hide",
  "Cataclysm":"S_WP_SP_DefenceAttack",
  "Chain Hook":"S_WP_SW_MoveSkill_AA",
  "Chain Lightning":"S_WP_ST_MainAttack_AA",
  "Chain Strike":"S_WP_GT_ChainAttack",
  "Chaos stiften":"S_WP_SP_DefenceAttack_SP",
  "Chaosschild":"S_WP_WA_DefenceAction",
  "Chaotic Shield":"S_WP_WA_DefenceAction",
  "Charging Slash":"S_WP_SW2_UpperAttack_SP",
  "Clay's Salvation":"S_WP_WA_GR_S_HealAll",
  "Clays Erl\u00f6sung":"S_WP_WA_GR_S_HealAll",
  "Cleaving Moonlight":"S_WP_DA_SpinAttack",
  "Cold Warrior":"S_KN_CO_Focusattack_AA",
  "Collision Shot":"S_WP_CR_BuckShot_SP_2",
  "Concentrated Barrier":"S_WP_SH_BuffAttack_SP",
  "Concentration Stance":"S_WP_BO_SiegeMode",
  "Constellation Link":"S_WP_ORB_Passive_SoulLink",
  "Constricting Tempest":"S_WP_SP_PushAttack_SP_1",
  "Controlling Rake":"S_WP_SW_MoveSkill_SP",
  "Corrupt Nail":"S_WP_CR_S_WeakenAccuracy",
  "Corrupted Magic Circle":"S_WP_WA_CurseArea_AA",
  "Counter Barrier":"S_WP_SH_BuffAttack_AA",
  "Cradle of Stars":"S_WP_ORB_Passive_HpUp",
  "Culling Arc":"S_WP_SP_ThrustPull",
  "Curse Explosion":"S_WP_WA_GR_CurseBurst_AA",
  "Curse Resonance":"S_WP_WA_AdditionalBurst",
  "Cursed Nightmare":"S_WP_WA_Sleep_AA",
  "Cyclonic Fury":"S_WP_SP_RapidAttack",
  "DaVinci's Chill":"S_WP_SW2_ShieldBuff_SP",
  "DaVinci's Courage":"S_WP_SW2_ShieldBuff_AA",
  "DaVincis K\u00fchle":"S_WP_SW2_ShieldBuff_SP",
  "Deadly Marker":"S_WP_BO_AttackMark",
  "Death Blow":"S_WP_SW2_S_CounterAttack_AA",
  "Death From Above":"S_WP_SP_DropAttack",
  "Death Knell":"S_WP_SP_KillBonus",
  "Decaying Touch":"S_WP_WA_CurseArea_SP",
  "Decisive Bombardment":"WP_BO_S_PowerShot_Charge_SP",
  "Decisive Sniping":"S_WP_BO_PowerShot_AA",
  "Desperate Clash":"S_WP_SH_PushAttack_SP",
  "Destructive Fang":"S_WP_DA_PoisonTargetOffHandAttack",
  "Detect Vulnerability":"S_WP_DA_CriticalOffHandAttack",
  "Detection":"S_WP_CR_AfterImage",
  "Detonation Mark":"S_WP_CR_ArmorBreakShot_SP",
  "Detonierendes Mal":"S_WP_CR_ArmorBreakShot_SP",
  "Devastating Smash":"S_WP_SW2_LeapAttack",
  "Devastating Tornado":"S_WP_SW2_BladeDance_1",
  "Devoted Sanctuary":"S_WP_SW2_DamageReceive_SP",
  "Devoted Shield":"S_WP_BO_AbnormalShield",
  "Devotion and Emptiness":"S_WP_WA_GR_DayHealNightCurse_AA",
  "Distorted Sanctuary":"S_WP_BO_AuraDefenceUp_AA",
  "Distortion Veil":"S_WP_ORB_Active_Shield",
  "Donnernde Bombe":"S_WP_DA_DeadlyStrike_SP",
  "Durchbohrender Schlag":"S_WP_CR_CriticalAttack",
  "Durchbruch":"S_WP_GT_BattleSense",
  "Dynamik":"S_WP_GT_Observation",
  "Eagle Vision":"S_WP_CR_DistanceRangeAcc_AA",
  "Earth's Blessing":"S_WP_BO_NatureForce",
  "Earthquake":"S_WP_GT_Earthquake",
  "Echobarriere":"S_WP_ST_S_SilenceToleranceBuff",
  "Echoes of Distortion":"S_WP_ORB_Active_TimeDelay_SP_1",
  "Echoic Barrier":"S_WP_ST_S_SilenceToleranceBuff",
  "Echos der Verzerrung":"S_WP_ORB_Active_TimeDelay_SP_1",
  "Eclipse of Blood":"S_WP_GT_EclipseOfBlood",
  "Edle Belebung":"S_WP_WA_GR_HealEfficiencyByMaxCost",
  "Eid des Heiligen":"S_WP_WA_HealEffectUpWhenSkillDamageTaken",
  "Ein-Zoll-Schlag":"S_WP_GT_OneInchPunch",
  "Eine Chance auf den Sieg":"S_WP_SW_SH_S_DoubleChanceAttack_1",
  "Einengender Sturm":"S_WP_SP_PushAttack_SP_1",
  "Eisenparieren":"S_WP_SW2_Defense_AA",
  "Eisgebundene R\u00fcstung":"S_WP_ST_IceFreeze",
  "Eisgebundenes Grab":"S_WP_ST_IceFreeze",
  "Eisspeer":"S_WP_ST_IceSpear",
  "Eisspeer-Bombardement":"S_WP_ST_IceSpear_SP",
  "Eistornado":"S_WP_SW2_SpinAttack_SP",
  "Elemental Awakening":"S_WP_ST_ElementalFusion",
  "Elementarerweckung":"S_WP_ST_ElementalFusion",
  "Enchanting Time":"S_WP_WA_GR_S_Decay_SP",
  "Enforcer":"S_WP_SP_AbnormalTolerance_SP2",
  "Ensnaring Arrow":"S_WP_BO_BindShot_AA",
  "Entschlossener Scharfschuss":"S_WP_BO_PowerShot_AA",
  "Entschlossenes Bombardement":"WP_BO_S_PowerShot_Charge_SP",
  "Erdbeben":"S_WP_GT_Earthquake",
  "Erfassung":"S_WP_CR_AfterImage",
  "Ergebener Schild":"S_WP_BO_AbnormalShield",
  "Erl\u00f6sende Barriere":"S_WP_ST_BringSkill_SP",
  "Erl\u00f6sungskette":"S_WP_ST_BringSkill",
  "Eternal Veil":"S_WP_ORB_Passive_ShieldUp",
  "Ewiger Schleier":"S_WP_ORB_Passive_ShieldUp",
  "Explosive Flurry":"S_WP_GT_GatlingAttack",
  "Explosive Fury":"S_WP_SP_RapidThrust_SP_2",
  "Explosive Trap":"S_WP_CR_TauntTrap",
  "Explosiver Wirbel":"S_WP_GT_GatlingAttack",
  "Explosiver Zorn":"S_WP_SP_RapidThrust_SP_2",
  "Eye of Ventius":"boro:eye-of-ventius",
  "Fallbeilklinge":"S_WP_SW2_PowerAttack",
  "Fatal Precision":"S_WP_SP_WeakenBonus",
  "Fatal Stigma":"S_WP_DA_DelayDamage",
  "Fegen":"S_WP_GT_Bulldozer",
  "Fesselnder Pfeil":"S_WP_BO_BindShot_AA",
  "Feuerballsperrfeuer":"S_WP_ST_FireCombo",
  "Fierce Clash":"S_WP_SH_PushAttack",
  "Fireball Barrage":"S_WP_ST_FireCombo",
  "Flame Condensation":"S_WP_ST_FireLightningForce_AA",
  "Flammenverdichtung":"S_WP_ST_FireLightningForce_AA",
  "Flash Arrow":"S_WP_BO_Detection",
  "Flash Wave":"S_WP_BO_Detection_SP",
  "Flinke Schritte":"S_WP_SP_MoveBuff",
  "Flinker Sprung":"S_WP_CR_Step_AA",
  "Fluchexplosion":"S_WP_WA_GR_CurseBurst_AA",
  "Fluchresonanz":"S_WP_WA_AdditionalBurst",
  "Focused Fire Bombs":"S_WP_ST_WideAreaAttack_SP",
  "Fokussierte Feuerbomben":"S_WP_ST_WideAreaAttack_SP",
  "Forbidden Sanctuary":"S_WP_ST_S_HitDamageReductionBuff",
  "Fortifying Shell":"S_WP_GT_TurtleStance",
  "Fountain of Life":"S_WP_WA_HealField",
  "Frenzied Lightning Wave":"S_WP_ST_WideAreaDebuffAttack_SP",
  "Frenzied Sword Dance":"WP_DA_DA_S_SonicAttack",
  "Frost Cleaving":"S_WP_SW2_GaiaCrash_SP",
  "Frost Master":"S_WP_ST_SlowDuration",
  "Frost Smokescreen":"S_WP_ST_S_AoeTeleport_AA",
  "Frostmeister":"S_WP_ST_SlowDuration",
  "Frostnebelschleier":"S_WP_ST_S_AoeTeleport_AA",
  "Full of Corruption":"S_WP_WA_GR_CurseKillBonus_AA",
  "Gaia Crash":"S_WP_SW2_GaiaCrash",
  "Gaiasturz":"S_WP_SW2_GaiaCrash",
  "Gale Rush":"S_WP_SP_DashAttack",
  "Geduldiger Block":"S_WP_SP_DefenceAction",
  "Geist des Donners":"S_WP_DA_ShadowChaser_SP",
  "Gerad's Patience":"S_WP_SH_BlockSucceedTolerance",
  "Gerad's Shield":"S_WP_SW_SH_DefenceSucceedBuff",
  "Gerads Geduld":"S_WP_SH_BlockSucceedTolerance",
  "Gerechte Wut":"S_WP_SH_ShieldBuff_SP",
  "Geschicktes Ausweichen":"S_WP_SW_TheCloserEvasionUP_AA",
  "Gesegnete Barriere":"S_WP_WA_DefenseUp",
  "Gewitterschlag":"S_WP_SP_PushAttack",
  "Giftspritze":"S_AS_SR_Burning__AA",
  "Gnadenloses Sperrfeuer":"S_WP_CR_FuriousFire",
  "Grausamer Zorn":"S_WP_SP_RapidThrust",
  "Gravity Star Destroyer":"S_WP_ORB_Active_RollingBall_SP_1",
  "Grenz\u00fcberwindung":"S_WP_BO_S_DoubleShot",
  "Guardian Defensive Wall":"S_WP_ORB_Active_PartyBarrier",
  "Guillotine Blade":"S_WP_SW2_PowerAttack",
  "Hardening":"S_WP_GT_Hardening",
  "Hauch der Verzweiflung":"S_WP_WA_Corruption_AA",
  "Healing Star":"S_WP_ORB_Active_OrbSummon_SP_1",
  "Healing Touch":"S_WP_BO_S_RegenHeal",
  "Healing Wave":"S_WP_ORB_Active_OrbitSlashHeal",
  "Heftiger Zusammensto\u00df":"S_WP_SH_PushAttack",
  "Heilende Ber\u00fchrung":"S_WP_BO_S_RegenHeal",
  "Heilender Stern":"S_WP_ORB_Active_OrbSummon_SP_1",
  "Hellfire Rain":"S_WP_ST_S_Meteor_SP",
  "Hieb der Leere":"S_WP_ORB_Active_OrbitSlash",
  "High Focus":"S_WP_ST_GlobalCoolDownBuff",
  "Hingebungsvolle Zuflucht":"S_WP_SW2_DamageReceive_SP",
  "Hoher Fokus":"S_WP_ST_GlobalCoolDownBuff",
  "H\u00f6llenfeuerregen":"S_WP_ST_S_Meteor_SP",
  "H\u00f6llischer Meteor":"S_WP_ST_S_Meteor",
  "Ice Spear":"S_WP_ST_IceSpear",
  "Ice Spear Bombardment":"S_WP_ST_IceSpear_SP",
  "Ice Tornado":"S_WP_SW2_SpinAttack_SP",
  "Icebound Armor":"S_WP_ST_IceFreeze",
  "Icebound Tomb":"S_WP_ST_IceFreeze",
  "Immortal Pride":"WP_SW_S_MaxHealthUp",
  "Impenetrable":"S_WP_SW_SH_S_AroundCountBuff",
  "Imposing Form":"S_WP_SP_TwoHandWeapon",
  "Incapacitate":"S_WP_GT_Disarm",
  "Indomitable Armor":"S_WP_SW2_HittedBuff",
  "Infernal Meteor":"S_WP_ST_S_Meteor",
  "Inferno Wave":"S_WP_ST_WideAreaDebuffAttack_AA",
  "Infernowelle":"S_WP_ST_WideAreaDebuffAttack_AA",
  "Inject Venom":"S_AS_SR_Burning__AA",
  "Inner Peace":"S_WP_ST_ManaRengeUp_AA",
  "Innerer Frieden":"S_WP_ST_ManaRengeUp_AA",
  "Instinkt des Assassinen":"S_WP_DA_MeleeAccuracy_AA",
  "Interstellar Explosion":"S_WP_ORB_Active_OrbExplosion",
  "Interstellare Explosion":"S_WP_ORB_Active_OrbExplosion",
  "Invincible Wall":"S_WP_WA_MagicShield_SP",
  "Iron Point Parry":"S_WP_SW2_Defense_AA",
  "Janice's Rage":"S_WP_WA_GR_S_HealAll_SP",
  "Janice\u2019 Wut":"S_WP_WA_GR_S_HealAll_SP",
  "Javelin Inferno":"S_WP_SP_SpearThrower_SP",
  "Javelin Surge":"S_WP_SP_SpearThrower",
  "Judgment Lightning":"S_WP_ST_PowerAttack",
  "Jumping Chain":"S_WP_ST_BringSkill",
  "Kalter Krieger":"S_KN_CO_Focusattack_AA",
  "Karmic Haze":"S_WP_WA_GR_CurseSpread",
  "Karmischer Hauch":"S_WP_WA_GR_CurseSpread",
  "Kettenblitzschlag":"S_WP_ST_MainAttack_AA",
  "Kettenhaken":"S_WP_SW_MoveSkill_AA",
  "Kettenschlag":"S_WP_GT_ChainAttack",
  "Klinge blocken":"S_WP_DA_CounterMove_ActionSkill_Guard_AA",
  "Knife Throwing":"S_WP_DA_PoisonDagger_AA",
  "Kn\u00f6chelhieb":"S_WP_DA_LegAttack",
  "Kollisionsschuss":"S_WP_CR_BuckShot_SP_2",
  "Konstellation beschw\u00f6ren":"S_WP_ORB_Active_OrbShoot",
  "Konstellations-Verbindung":"S_WP_ORB_Passive_SoulLink",
  "Konterbarriere":"S_WP_SH_BuffAttack_AA",
  "Konzentrationshaltung":"S_WP_BO_SiegeMode",
  "Konzentrierte Barriere":"S_WP_SH_BuffAttack_SP",
  "Korrupter Nagel":"S_WP_CR_S_WeakenAccuracy",
  "K\u00f6rpertraining":"S_WP_GT_BasicTraining",
  "K\u00fchne Pr\u00fcgel":"S_WP_SW2_MainAttack_AA",
  "Lebensbrunnen":"S_WP_WA_HealField",
  "Lenkende Harke":"S_WP_SW_MoveSkill_SP",
  "Lightning Infusion":"S_WP_DA_PoisonEnchant_SP",
  "Lightning Throw":"S_WP_DA_PoisonDagger_SP",
  "Limit Break":"S_WP_BO_S_DoubleShot",
  "Locken des Geistes":"S_WP_WA_GR_CurseDuration_AA",
  "Macht der Natur":"S_WP_CR_PeaceTimeBuff_AA",
  "Mad Sword Dance":"S_WP_DA_SonicAttack_SP",
  "Malice Surge":"S_WP_SP_AttackedBuff",
  "Mana Amp":"S_WP_ST_MaxManaUp_AA",
  "Mana Exchange":"S_WP_CR_BloodToSoul",
  "Mana-Austausch":"S_WP_CR_BloodToSoul",
  "Manaball Eruption":"S_WP_ST_AddProjectile_AA",
  "Manasph\u00e4renausbruch":"S_WP_ST_AddProjectile_AA",
  "Manaverst\u00e4rkung":"S_WP_ST_MaxManaUp_AA",
  "Master of Provocation":"S_WP_GT_TauntMaster",
  "Meister der Provokation":"S_WP_GT_TauntMaster",
  "Merciless Barrage":"S_WP_CR_FuriousFire",
  "Messerwerfen":"S_WP_DA_PoisonDagger_AA",
  "Milchstra\u00dfe":"S_WP_ORB_Active_OrbShoot_SP_1",
  "Milky Way":"S_WP_ORB_Active_OrbShoot_SP_1",
  "Mobility Strike":"S_WP_GT_MoveAttack",
  "Momentum":"S_WP_GT_Observation",
  "Moral des Siegers":"S_WP_SW2_SkillSucceedRewardMana_AA",
  "Morale Boost":"S_WP_SH_CrashSucceedBuff",
  "Moralschub":"S_WP_SH_CrashSucceedBuff",
  "Mortal Mark":"S_WP_CR_ArmorBreakShot_AA",
  "Mortal Wrath":"S_WP_SP_LowHpAttack",
  "Mother Nature's Protest":"S_WP_CR_AddProjectile",
  "Multi-Shot":"S_WP_CR_BuckShot_AA",
  "Multischuss":"S_WP_CR_BuckShot_AA",
  "Murderous Energy":"S_WP_DA_PoisonBuff_AA",
  "Mut des DaVinci":"S_WP_SW2_ShieldBuff_AA",
  "Mystic Shield":"S_WP_ST_defenceAction_AA",
  "Mystischer Schild":"S_WP_ST_defenceAction_AA",
  "M\u00f6rderische Energie":"S_WP_DA_PoisonBuff_AA",
  "Nature's Blessing":"S_WP_BO_RegenAura_AA",
  "Nature's Power":"S_WP_CR_PeaceTimeBuff_AA",
  "Nimble Leap":"S_WP_CR_Step_AA",
  "Nimble Steps":"S_WP_SP_MoveBuff",
  "Noble Revival":"S_WP_WA_GR_HealEfficiencyByMaxCost",
  "One-Inch Punch":"S_WP_GT_OneInchPunch",
  "Overtaker":"S_WP_BO_DefenceAction_AA",
  "Patient Block":"S_WP_SP_DefenceAction",
  "Pfeilwirbel":"S_WP_BO_TornadoShot",
  "Phantom Smokescreen":"S_WP_DA_Smoke",
  "Phantomnebelwand":"S_WP_DA_Smoke",
  "Phoenix Barrage":"S_WP_SP_RapidAttack_SP",
  "Physique Training":"S_WP_GT_BasicTraining",
  "Ph\u00f6nix-Sperrfeuer":"S_WP_SP_RapidAttack_SP",
  "Piercing Strike":"S_WP_CR_CriticalAttack",
  "Precision Dash":"S_KN_SR_DashAttack_AA",
  "Protest von Mutter Natur":"S_WP_CR_AddProjectile",
  "Provoking Roar":"S_WP_SW_SH_TauntBuff_AA",
  "Provozierendes Br\u00fcllen":"S_WP_SW_SH_TauntBuff_AA",
  "Pr\u00e4zisionssprint":"S_KN_SR_DashAttack_AA",
  "Puls der Schlachtfelder":"S_WP_SP_AuraBuff",
  "Pulsating Galaxy":"S_WP_ORB_Passive_CastingMastery",
  "Pulse of the Battlegrounds":"S_WP_SP_AuraBuff",
  "Pulsierende Galaxie":"S_WP_ORB_Passive_CastingMastery",
  "Purifying Touch":"S_WP_BO_AbnormalDispel",
  "Quick Fire":"S_WP_CR_RapidShot_AA",
  "Raging Frenzy":"S_WP_SW2_StunSuccecsDamageBoost",
  "Rapid Shot":"S_WP_CR_BuckShot_SP",
  "Rapidfire Stance":"S_WP_BO_InplaceAttack_AA",
  "Rasche Heilung":"S_WP_WA_GR_S_Heal_AA",
  "Rasende Blitzwelle":"S_WP_ST_WideAreaDebuffAttack_SP",
  "Raum\u00fcbergang":"S_WP_ORB_Active_Phasing_SP_1",
  "Ray of Disaster":"S_WP_WA_LinkLaser_SP",
  "Recoil Shot":"WP_CR_AddShot",
  "Redemptive Barrier":"S_WP_ST_BringSkill_SP",
  "Reihen-Brandbomben":"S_WP_ST_WideAreaAttack_AA",
  "Reinigende Ber\u00fchrung":"S_WP_BO_AbnormalDispel",
  "Resilient Mind":"S_WP_SH_BlockSucceedRewardMana_AA",
  "Restoring Constellation":"S_WP_ORB_Active_Restoration",
  "Retaliatory Strike":"S_WP_SP_ComboBuff",
  "Rift Fracture":"S_WP_ORB_Passive_ExpandRift",
  "Righteous Fury":"S_WP_SH_ShieldBuff_SP",
  "Rising Slash":"S_WP_SP_CrossAttack",
  "Robust Constitution":"S_WP_SW2_HPMaxUP_AA",
  "Robuste Konstitution":"S_WP_SW2_HPMaxUP_AA",
  "Roxie's Arrowhead":"S_WP_BO_WindBonusProjectile",
  "Roxies Pfeilspitze":"S_WP_BO_WindBonusProjectile",
  "Rupturing Parry":"S_WP_CR_DefenseAction_Evasion_AA",
  "R\u00fccksto\u00df-Schuss":"WP_CR_AddShot",
  "Saint's Oath":"S_WP_WA_HealEffectUpWhenSkillDamageTaken",
  "Salvation Chain":"S_WP_ST_BringSkill",
  "Satellit beschw\u00f6ren":"S_WP_ORB_Active_Satellite",
  "Schattenhafter Geist":"S_WP_DA_ShadowChaser",
  "Schattenl\u00e4ufer":"S_WP_DA_MoveSkillEvasion_AA",
  "Schattenstreich":"S_WP_DA_BlinkStrike_AA",
  "Schild von Gerad":"S_WP_SW_SH_DefenceSucceedBuff",
  "Schildangriff":"S_WP_SW_SH_S_DebuffAttack_AA",
  "Schildwurf":"S_WP_SW_SH_S_ShieldThrow",
  "Schild\u00fcberlebenstechnik":"S_WP_SW_DefenceAction_AA",
  "Schlachtender Bogen":"S_WP_SP_ThrustPull",
  "Schlachthieb":"S_WP_SP_CrossAttack_SP",
  "Schmetternder Speer":"S_WP_SP_SpearThrower",
  "Schneller Schuss":"S_WP_CR_BuckShot_SP",
  "Schnellfeuer":"S_WP_CR_RapidShot_AA",
  "Schnellfeuerhaltung":"S_WP_BO_InplaceAttack_AA",
  "Schwachpunktschuss":"S_WP_CR_WeakPointShot",
  "Schwachstelle orten":"S_WP_DA_CriticalOffHandAttack",
  "Schwerkraft-Sternenzerst\u00f6rer":"S_WP_ORB_Active_RollingBall_SP_1",
  "Sch\u00fctzender Panzer":"S_WP_GT_TurtleStance",
  "Segen der Erde":"S_WP_BO_NatureForce",
  "Segen der Natur":"S_WP_BO_RegenAura_AA",
  "Segen der Unsterblichkeit":"S_WP_SW_S_MaxHealthUp_SP",
  "Selbstlose Seele":"S_WP_WA_SupportAllyCostRegenUp",
  "Selbstlose Streuung":"S_WP_CR_GhostWalk_AA",
  "Selfless Diffusion":"S_WP_CR_GhostWalk_AA",
  "Selfless Soul":"S_WP_WA_SupportAllyCostRegenUp",
  "Sentinel's Bastion":"S_WP_SP_AbnormalTolerance_SP",
  "Serial Fire Bombs":"S_WP_ST_WideAreaAttack_AA",
  "Shadow Strike":"S_WP_DA_BlinkStrike_AA",
  "Shadow Walker":"S_WP_DA_MoveSkillEvasion_AA",
  "Shield Strike":"S_WP_SW_SH_S_DebuffAttack_AA",
  "Shield Survival Technique":"S_WP_SW_DefenceAction_AA",
  "Shield Throw":"S_WP_SW_SH_S_ShieldThrow",
  "Short Jab":"S_WP_GT_ChargeAttack",
  "Sinn des Scharfsch\u00fctzen":"S_WP_BO_DistanceCritical_AA",
  "Skillful Evasion":"S_WP_SW_TheCloserEvasionUP_AA",
  "Slaughtering Slash":"S_WP_SP_CrossAttack_SP",
  "Sniper's Sense":"S_WP_BO_DistanceCritical_AA",
  "Sonnenfinsternis des Blutes":"S_WP_GT_EclipseOfBlood",
  "Space Transition":"S_WP_ORB_Active_Phasing_SP_1",
  "Spaltbruch":"S_WP_ORB_Passive_ExpandRift",
  "Spaltender Frost":"S_WP_SW2_GaiaCrash_SP",
  "Spaltendes Mondlicht":"S_WP_DA_SpinAttack",
  "Spectrum of Agony":"S_WP_SW_TauntBuff_Attack_AA",
  "Speerinferno":"S_WP_SP_SpearThrower_SP",
  "Spektrum der Qual":"S_WP_SW_TauntBuff_Attack_AA",
  "Sprengfalle":"S_WP_CR_TauntTrap",
  "Springende Kette":"S_WP_ST_BringSkill",
  "Sprint des Barbaren":"S_WP_SW2_SkillMaster",
  "Stalwart Bastion":"S_WP_SH_ShieldBuff",
  "Standhafte Bastion":"S_WP_SH_ShieldBuff",
  "Star Destroyer":"S_WP_ORB_Active_RollingBall",
  "Starcalling":"S_WP_ORB_Active_OrbSummon",
  "Steady Aim":"S_WP_BO_BindAccuracyBoost_AA",
  "Stellar Cycle":"S_WP_ORB_Passive_Circulation",
  "Stellar Dash":"S_WP_ORB_Active_Laser",
  "Stellar Echo":"S_WP_ORB_Passive_SubProjectile",
  "Sternenruf":"S_WP_ORB_Active_OrbSummon",
  "Sternenzerst\u00f6rer":"S_WP_ORB_Active_RollingBall",
  "Storm Current":"S_WP_CR_Gale_Buff",
  "Strafing":"S_WP_BO_MultiShot_AA",
  "Strahl des Verderbens":"S_WP_WA_LinkLaser_SP",
  "Strategic Rush":"S_WP_SW_SH_DashAttack_AA",
  "Strategischer Ansturm":"S_WP_SW_SH_DashAttack_AA",
  "Stunning Blow":"S_KN_SR_ShockStun_AA",
  "Sturm-Sprint":"S_WP_SP_DashAttack",
  "Sturmstr\u00f6mung":"S_WP_CR_Gale_Buff",
  "St\u00fcrmischer Schlag":"S_WP_SW2_UpperAttack_SP",
  "St\u00fcrmischer Zorn":"S_WP_SP_RapidAttack",
  "Summon Constellation":"S_WP_ORB_Active_OrbShoot",
  "Summon Guardian Satellite":"S_WP_ORB_Active_Satellite",
  "Summon Satellite":"S_WP_ORB_Active_Satellite",
  "Supernova Collapse":"S_WP_ORB_Active_GravityCollapse",
  "Supernova-Zusammenbruch":"S_WP_ORB_Active_GravityCollapse",
  "Suppressing Strike":"S_WP_SW2_Stun_Buff",
  "Sweep":"S_WP_GT_Bulldozer",
  "Swift Healing":"S_WP_WA_GR_S_Heal_AA",
  "Tarnmantel":"S_AS_SR_Hide",
  "Taunt":"S_WP_GT_Taunt",
  "Tempest Strike":"S_WP_SP_PushAttack",
  "Temporal Leap":"S_WP_ORB_Active_Phasing",
  "Threat Boost":"S_WP_GT_AggroBuff",
  "Thunder Spirit":"S_WP_DA_ShadowChaser_SP",
  "Thundering Bomb":"S_WP_DA_DeadlyStrike_SP",
  "Time Dilation":"S_WP_ORB_Active_TimeDelay",
  "Time for Punishment":"S_WP_WA_Decay",
  "Tobende Raserei":"S_WP_SW2_StunSuccecsDamageBoost",
  "Tod von oben":"S_WP_SP_DropAttack",
  "Todesschlag":"S_WP_SW2_S_CounterAttack_AA",
  "Tornado":"S_WP_BO_TornadoShot_SP",
  "Totenglocke":"S_WP_SP_KillBonus",
  "Touch of Despair":"S_WP_WA_Corruption_AA",
  "Trance":"S_WP_GT_S_BattleTrance",
  "T\u00f6dliche Markierung":"S_WP_BO_AttackMark",
  "T\u00f6dliche Pr\u00e4zision":"S_WP_SP_WeakenBonus",
  "T\u00f6dlicher Zorn":"S_WP_SP_LowHpAttack",
  "T\u00f6dliches Mal":"S_WP_CR_ArmorBreakShot_AA",
  "T\u00f6dliches Stigma":"S_WP_DA_DelayDamage",
  "Umbral Spirit":"S_WP_DA_ShadowChaser",
  "Unberechenbarkeit":"S_WP_GT_EverChanging",
  "Unbeugsamer W\u00e4chter":"S_WP_SP_AbnormalTolerance",
  "Unbezwingbare R\u00fcstung":"S_WP_SW2_HittedBuff",
  "Unbezwingbare Wand":"S_WP_WA_MagicShield_SP",
  "Undurchdringlich":"S_WP_SW_SH_S_AroundCountBuff",
  "Unersch\u00fctterliche Haltung":"S_WP_GT_CounterMove",
  "Unpredictable":"S_WP_GT_EverChanging",
  "Unshakable Stance":"S_WP_GT_CounterMove",
  "Unsterblicher Stolz":"WP_SW_S_MaxHealthUp",
  "Unterdr\u00fcckender Schlag":"S_WP_SW2_Stun_Buff",
  "Unyielding Sentinel":"S_WP_SP_AbnormalTolerance",
  "Urteilsblitz":"S_WP_ST_PowerAttack",
  "Valiant Brawl":"S_WP_SW2_MainAttack_AA",
  "Vampiric Contract":"S_WP_WA_GR_CurseAttackHeal_AA",
  "Vampiric Strike":"S_WP_DA_BloodStrike",
  "Vampirischer Vertrag":"S_WP_WA_GR_CurseAttackHeal_AA",
  "Vampirschlag":"S_WP_DA_BloodStrike",
  "Verbotenes Heiligtum":"S_WP_ST_S_HitDamageReductionBuff",
  "Verdorbener magischer Kreis":"S_WP_WA_CurseArea_AA",
  "Verfluchter Alptraum":"S_WP_WA_Sleep_AA",
  "Vergeltender Hieb":"S_WP_SP_ComboBuff",
  "Verheerung":"S_WP_SP_DefenceAttack",
  "Verh\u00e4rtung":"S_WP_GT_Hardening",
  "Vernichtender Schlag":"S_WP_SW2_LeapAttack",
  "Verr\u00fcckter Schwerttanz":"S_WP_DA_SonicAttack_SP",
  "Verspotten":"S_WP_GT_Taunt",
  "Verst\u00e4rkungsschleier":"S_WP_ORB_Active_Shield_SP_1",
  "Verw\u00fcstender Tornado":"S_WP_SW2_BladeDance_1",
  "Verzauberungszeit":"S_WP_WA_GR_S_Decay_SP",
  "Verzerrtes Heiligtum":"S_WP_BO_AuraDefenceUp_AA",
  "Verzerrungsschleier":"S_WP_ORB_Active_Shield",
  "Verzweifelter Zusammensto\u00df":"S_WP_SH_PushAttack_SP",
  "Vicious Fury":"S_WP_SP_RapidThrust",
  "Victor's Morale":"S_WP_SW2_SkillSucceedRewardMana_AA",
  "Vital Force":"S_KN_CO_BounceAttack_AA",
  "Vitalkraft":"S_KN_CO_BounceAttack_AA",
  "Void Slash":"S_WP_ORB_Active_OrbitSlash",
  "Voller Korruption":"S_WP_WA_GR_CurseKillBonus_AA",
  "Vollstrecker":"S_WP_SP_AbnormalTolerance_SP2",
  "Vorwitzige Retorte":"S_WP_SW_SH_S_ManaAttack",
  "Weak Point Shot":"S_WP_CR_WeakPointShot",
  "Welle der Heilung":"S_WP_ORB_Active_OrbitSlashHeal",
  "Whirling Shield":"S_WP_SW_SH_S_ShieldThrow_SP",
  "Wiederherstellungs-Konstellation":"S_WP_ORB_Active_Restoration",
  "Wiege der Sterne":"S_WP_ORB_Passive_HpUp",
  "Wild Barrage":"S_WP_CR_FuriousFire_SP_2",
  "Wilder Schwerttanz":"WP_DA_DA_S_SonicAttack",
  "Wildes Sperrfeuer":"S_WP_CR_FuriousFire_SP_2",
  "Willbreaker":"S_WP_SW2_DefenseDebuffAttack",
  "Willensbrecher":"S_WP_SW2_DefenseDebuffAttack",
  "Wind Snatcher":"S_WP_CR_RobShot",
  "Winddieb":"S_WP_CR_RobShot",
  "Wirbelnder Schild":"S_WP_SW_SH_S_ShieldThrow_SP",
  "Witty Retort":"S_WP_SW_SH_S_ManaAttack",
  "Wraith's Beckon":"S_WP_WA_GR_CurseDuration_AA",
  "Wrathful Edge":"S_WP_DA_CriticalDamageUp",
  "Wreak Havoc":"S_WP_SP_DefenceAttack_SP",
  "W\u00e4chter-Satellit beschw\u00f6ren":"S_WP_ORB_Active_Satellite",
  "W\u00e4chter-Verteidigungsmauer":"S_WP_ORB_Active_PartyBarrier",
  "W\u00e4chterbastion":"S_WP_SP_AbnormalTolerance_SP",
  "Zahn der Zerst\u00f6rung":"S_WP_DA_PoisonTargetOffHandAttack",
  "Zeit f\u00fcr Bestrafung":"S_WP_WA_Decay",
  "Zeiterweiterung":"S_WP_ORB_Active_TimeDelay",
  "Zeitsprung":"S_WP_ORB_Active_Phasing",
  "Zephyr's Nock":"S_WP_BO_StrongShot_AA",
  "Zephyrs Nockpunkt":"S_WP_BO_StrongShot_AA",
  "Zielsicherheit":"S_WP_BO_BindAccuracyBoost_AA",
  "Zornige Schneide":"S_WP_DA_CriticalDamageUp",
  "\u00dcberwinder":"S_WP_BO_DefenceAction_AA",
  "Blade Storm":"boro:blade-storm",
  "Deadly Viper":"boro:deadly-viper",
  "Klingensturm":"boro:blade-storm",
  "Seelenernte des Silbernen Schnitters":"boro:soul-harvest",
  "Silver Reaper's Soul Harvest":"boro:soul-harvest",
  "T\u00f6dliche Viper":"boro:deadly-viper",
  "Agile Shot":"boro:agile-shot",
  "Agiler Schuss":"boro:agile-shot",
  "Blitzgeschwindigkeit":"boro:lightning-speed",
  "Corrupting Hit":"boro:corrupting-hit",
  "Destruction Spear":"boro:destruction-spear",
  "Drachenaufstieg":"boro:dragon-ascent",
  "Dragon Ascent":"boro:dragon-ascent",
  "Giftige Schneide":"boro:venomous-edge",
  "Lightning Speed":"boro:lightning-speed",
  "Venomous Edge":"boro:venomous-edge",
  "Verderbender Treffer":"boro:corrupting-hit",
  "Wave Shot":"WP_CR_AddShot",
  "Wellenschuss":"WP_CR_AddShot",
  "Zerst\u00f6rungsspeer":"boro:destruction-spear",
  "Absorbing Grasp":"boro:absorbing-grasp",
  "Absorbierender Griff":"boro:absorbing-grasp",
  "Abyssal Burst":"boro:abyssal-burst",
  "Ausbruch des Abgrunds":"boro:abyssal-burst",
  "Blood Explosion":"boro:blood-explosion",
  "Blood Spiral":"boro:blood-spiral",
  "Bloodstorm":"boro:bloodstorm",
  "Blutexplosion":"boro:blood-explosion",
  "Blutspirale":"boro:blood-spiral",
  "Blutsturm":"boro:bloodstorm",
  "Claw":"boro:claw",
  "Klaue":"boro:claw",
  "Consecutive Claws":"boro:consecutive-claws",
  "Consecutive Hits":"boro:consecutive-hits",
  "Copy Satellite":"S_WP_ORB_Active_Satellite",
  "Corrupted Obliteration":"boro:corrupted-obliteration",
  "Counterattack Spell":"S_WP_WA_DefenceAction",
  "Dimensional Bomb":"boro:dimensional-bomb",
  "Dimensionsbombe":"boro:dimensional-bomb",
  "Fortlaufende Klauen":"boro:consecutive-claws",
  "Fortlaufende Treffer":"boro:consecutive-hits",
  "Gegenangriffszauber":"S_WP_WA_DefenceAction",
  "Satellit kopieren":"S_WP_ORB_Active_Satellite",
  "Verderbte Ausl\u00f6schung":"boro:corrupted-obliteration",
  "Doppelhieb":"boro:double-slash",
  "Double Slash":"boro:double-slash",
  "Enraged Tevent's Hunger":"boro:tevents-hunger-enraged",
  "Evaporation":"boro:evaporation",
  "Murderous Draw":"S_WP_SW2_Defense_AA",
  "M\u00f6rderisches Ziehen":"S_WP_SW2_Defense_AA",
  "Tevents Hunger (Erz\u00fcrnt)":"boro:tevents-hunger-enraged",
  "Verdunstung":"boro:evaporation",
  "Afterimage":"boro:afterimage",
  "Ausl\u00f6schender Sumpf":"boro:obliterating-swamp",
  "Faulheitsk\u00e4fig":"boro:slothful-cage",
  "Hieb":"boro:slash",
  "Hiebwelle":"boro:slash-wave",
  "Mutilation":"boro:mutilation",
  "Nachbild":"boro:afterimage",
  "Obliterating Swamp":"boro:obliterating-swamp",
  "Schwingen":"boro:swing",
  "Slash":"boro:slash",
  "Slash Wave":"boro:slash-wave",
  "Slothful Cage":"boro:slothful-cage",
  "Spiral Slash":"boro:spiral-slash",
  "Spiralhieb":"boro:spiral-slash",
  "Swing":"boro:swing",
  "Verst\u00fcmmelung":"boro:mutilation",
  "Blood Talon":"boro:blood-talon",
  "Blutklaue":"boro:blood-talon",
  "Enraged Tevent's Despair Trap":"boro:despair-trap-enraged",
  "Heiliger magischer Kreis":"boro:sacred-magic-circle",
  "Sacred Magic Circle":"boro:sacred-magic-circle",
  "Verzweiflungsfalle des Tevent (Erzürnt)":"boro:despair-trap-enraged",
  /* Derselbe Skill in zwei Zustaenden: "Klinge blocken wird zu
     Giftdolch", sagt der Tooltip. Gemessen 13,3 von 255 zwischen
     dem eigenen Bild und dem vorhandenen Symbol, fremde liegen bei
     63 bis 65. Also ein Verweis, kein zweites Bild. */
  "Giftdolch":"S_WP_DA_CounterMove_ActionSkill_Guard_AA",
  "Poison Dagger":"S_WP_DA_CounterMove_ActionSkill_Guard_AA",
  /* Zustaende zweier Abwehrfaehigkeiten, keine eigenen Skills:
     Mystischer Schild wird fuer drei Sekunden zu
     Blitzspitzhacke oder Verbrennungskugel, Eisenparieren
     aktiviert Stuermendes Ziehen. Steht so in den Tooltips des
     Spiels; nachgemessen 18,6 und 12,0 von 255 zwischen den
     Bildern dort und den vorhandenen Symbolen, fremde liegen
     bei 62 bis 72. */
  "Blitzspitzhacke":"S_WP_ST_defenceAction_AA",
  "Charging Draw":"S_WP_SW2_Defense_AA",
  "Lightning Pick":"S_WP_ST_defenceAction_AA",
  "Scorching Sphere":"S_WP_ST_defenceAction_AA",
  "St\u00fcrmendes Ziehen":"S_WP_SW2_Defense_AA",
  "Verbrennungskugel":"S_WP_ST_defenceAction_AA"
};
/* Der Skillname kann englisch oder deutsch sein; beide stehen in der
   Tabelle. Wo nichts steht, gibt es kein Symbol - dann bleibt es bei der
   Farbmarke, die es immer schon gab. */
/* Fuer die Leinwand: ein geladenes Bildobjekt, oder null. Eine data-URL
   laedt sofort, aber nicht synchron - beim ersten Zeichnen ist sie noch
   nicht da. Sobald sie steht, wird einmal neu gezeichnet, gebuendelt
   ueber alle Symbole. Danach ist im.complete wahr und es passiert
   nichts mehr; eine Schleife kann daraus nicht werden. */
const ICON_CACHE = new Map();
let iconNachzeichnen = 0;
export function iconBild(name: string, sid?: string | null){
  const u = skillIcon(name, sid);
  if(!u) return null;
  let im = ICON_CACHE.get(u);
  if(im === undefined){
    im = new Image();
    im.onload = () => {
      clearTimeout(iconNachzeichnen);
      iconNachzeichnen = setTimeout(() => {
        if(typeof renderRotation === "function" && state.tab === "rotation")
          renderRotation();
      }, 0);
    };
    im.src = u;
    ICON_CACHE.set(u, im);
  }
  return (im.complete && im.naturalWidth) ? im : null;
}

/* Ein <img> mit dem Symbol, oder nichts. aria-hidden, weil der Name
   direkt daneben steht - ein Vorleser saehe sonst zweimal dasselbe. */
/* Ein Ding statt zweier: entweder das Bild in der Fassung oder, wenn
   es keines gibt, die volle Platte. Beide sind gleich gross und stehen
   an derselben Stelle. */
export function skillMark(name: string, sid?: string | null, farbe?: string, rest?: boolean){
  const u = skillIcon(name, sid);
  /* Das Bild hat Vorrang vor der Schraffur. Eine Rest-Zeile - Rang 13
     und weiter, wo die zwoelf Serienfarben aufgehoert haben - bekam
     hier zuerst die Schraffur STATT des Bildes, und damit verschwand
     bei jedem Skill ab Rang 13 das Symbol. Die Schraffur bleibt jetzt
     dem Fall ohne Bild; dass es eine Rest-Zeile ist, sagt ohnehin der
     Balken, der dasselbe Muster ueber seine ganze Laenge zeichnet. */
  if(rest && !u) return '<span class="sic leer hatch" aria-hidden="true"></span>';
  const c = rest ? "var(--series-rest)" : farbe;
  const stil = c ? ' style="--sic-c:'+c+'"' : "";
  return u
    ? '<img class="sic" src="'+u+'" alt="" aria-hidden="true"'+stil+'>'
    : '<span class="sic leer" aria-hidden="true"'+stil+'></span>';
}
/* Nach Skill-ID, nicht nach Name - das ist der genauere Schluessel,
   denn eine ID gehoert zu genau einer Waffe. Gebraucht wird er bei
   Standardschuss: die App kennt neun IDs dafuer, sechs Armbrust und drei
   Langbogen, und das Bild zeigt eine Armbrust. Am Namen aufgehaengt
   truege ein Langbogen-Standardschuss das Bild einer Armbrust. */
export const SKILL_ICON_SID: Record<string, string> = {
  "947450333":"boro:basic-shot-cb",
  "947515856":"boro:basic-shot-cb",
  "947525562":"boro:basic-shot-cb",
  "947581240":"boro:basic-shot-cb",
  "947843568":"boro:basic-shot-cb",
  "947909095":"boro:basic-shot-cb",
  "948361757":"boro:manaball-staff",
  "948692280":"boro:manaball-staff",
  "948823370":"boro:manaball-staff",
  "950614913":"boro:manaball-wand",
  "950745989":"boro:manaball-wand",
  "951925391":"boro:manaball-wand",
  /* Die Kennung, die ventiusPass() setzt - und nur dann, wenn
     zwei Treffer der Familie im Fenster auf dasselbe Ziel
     gehen. Ohne Erkennung bleibt die Zeile Entschlossener
     Scharfschuss und behaelt dessen Bild. */
  "boro:ventius":"boro:eye-of-ventius",
  /* Die drei Langbogen-IDs. Der Name "Standardschuss" traegt
     neun IDs und zwei Waffen, darum haengt das Bild hier und
     nicht am Namen - sonst zeigte ein Langbogenschuss eine
     Armbrust. Die zwei Bilder unterscheiden sich um 52 von
     255, sind also wirklich zwei. */
  "947457802":"boro:basic-shot-lb",
  "947523317":"boro:basic-shot-lb",
  "947551927":"boro:basic-shot-lb",
  "967879042":"boro:manaball-staff",
  "967944588":"boro:manaball-staff",
  "968862069":"boro:manaball-staff"
};

/* ---------- Skillkern-Symbole ----------
   Bild fuer 35 von 36 Kernen (Neugestaltung 28.09., Luecke 2.10; Nachtrag
   N2, 30.09.): geladen vom questlog-CDN mit Freigabe am 28.09.,
   erneuert am 30.09., einmal beim Bauen und eingebettet - die Seite laedt
   nichts. Die Bilder liegen unter
   https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Icon/Item_128/Misc/,
   neben jedem steht Item-ID und Dateiname. Die Originale sind 256 px
   (zwei 200 px, die zwei aeltesten 128 px), verkleinert auf 48 px als WebP
   (Qualitaet 0,9). Nur Bilddaten - kein Name aus Questlog wird gespeichert,
   die englischen Schluessel sind die aus SKILL_CORE (21-damage-table.ts).
   Zwei Kerne teilen sich ein Bild, weil sie am selben Item haengen
   (Perk_EA_35_431): Explosive Lightning Slash und Lightning
   Javelin.
   Ohne Bild bleibt "Ice Rain": drei Kerne ergeben im Log denselben Namen,
   jeder mit anderem Symbol, und das Log sagt nicht, welcher es war. Die
   Zeile behaelt die gezeichnete Marke (CORE_GEM). Die Kernprobe
   (scripts/test-kerne-core.mjs) haelt beides fest: jeder Kern hat ein Bild
   oder steht in ihrer Ausnahmeliste, jedes Bild ist ein WebP von 48 x 48
   und hoechstens 6 kB. Eye of Ventius wird erst zur Laufzeit angelegt;
   coreBadge() findet sein Bild ueber denselben Namen. Die Tabelle
   KERN_BILD steht in ../spielbilder; oben mit SKILL_ICON_BILD weitergereicht. */
