
/* ---------- die Waffen aus demselben Feed ----------
   Besser als die Tabelle aus dem eigenen Export und deshalb davor: sie kennt
   Gauntlet (dort standen alle Gauntlet-Skills als "other"), sie traegt
   deutsche Namen, und sie enthaelt keine Baumknoten. */
export const SKILL_WAFFE_Q: Record<string, string> = {
  "A Shot at Victory":"Sword and Shield",
  "Abgrundspalt":"Spear",
  "Abyssal Cleave":"Spear",
  "Adlersicht":"Crossbow",
  "Aegis Shield":"Sword and Shield",
  "Aegis-Schild":"Sword and Shield",
  "Ambidexterity":"Crossbow",
  "Amplification Veil":"Orb",
  "Andacht und Leere":"Wand and Tome",
  "Ankle Strike":"Dagger",
  "Annihilating Slash":"Sword and Shield",
  "Annihilation Barrage Shot":"Crossbow",
  "Annihilation Blade":"Sword and Shield",
  "Ansteigender Hieb":"Spear",
  "Arrow Vortex":"Longbow",
  "Ascending Cleave":"Spear",
  "Ascending Slash":"Greatsword",
  "Asceticism":"Staff",
  "Askese":"Staff",
  "Assassin's Instincts":"Dagger",
  "Assassin's Step":"Dagger",
  "Assassination Stance":"Dagger",
  "Assassinenschritt":"Dagger",
  "Astral Overseer":"Orb",
  "Astralaufseher":"Orb",
  "Astralecho":"Orb",
  "Astralsprint":"Orb",
  "Astralzyklus":"Orb",
  "Attentatshaltung":"Dagger",
  "Aufsteigender Hieb":"Greatsword",
  "Aufsteigender Spalt":"Spear",
  "Aufwallen der Bosheit":"Spear",
  "Auge von Ventius":"Longbow",
  "Ausl\u00f6schender Hieb":"Sword and Shield",
  "Ausl\u00f6schender Sperrfeuerschuss":"Crossbow",
  "Ausl\u00f6schendes Schwert":"Sword and Shield",
  "Ausschalten":"Gauntlet",
  "Barbarian's Dash":"Greatsword",
  "Barrier":"Orb",
  "Barriere":"Orb",
  "Bedrohungsschub":"Gauntlet",
  "Beeindruckende Form":"Spear",
  "Begin the Hunt":"Longbow",
  "Beginne die Jagd":"Longbow",
  "Beidh\u00e4ndigkeit":"Crossbow",
  "Belastbarer Geist":"Sword and Shield",
  "Ber\u00fchrung des Verfalls":"Wand and Tome",
  "Beschuss":"Longbow",
  "Bet\u00e4ubender Schlag":"Greatsword",
  "Beweglichkeitsschlag":"Gauntlet",
  "Blessed Barrier":"Wand and Tome",
  "Blessing of Immortality":"Sword and Shield",
  "Blitz":"Longbow",
  "Blitzdurchdringung":"Dagger",
  "Blitzpfeil":"Longbow",
  "Blitzwelle":"Longbow",
  "Blitzwurf":"Dagger",
  "Block Blade":"Dagger",
  "Blood Devotion":"Greatsword",
  "Bloodleech Aura":"Spear",
  "Bloodlust":"Crossbow",
  "Bloody Claws":"Gauntlet",
  "Blutdurst":"Crossbow",
  "Blutige Hingabe":"Greatsword",
  "Blutige Krallen":"Gauntlet",
  "Blutsaugeraura":"Spear",
  "Brandnebelschleier":"Staff",
  "Breakthrough":"Gauntlet",
  "Brechendes Parieren":"Crossbow",
  "Brutal Arrow":"Longbow",
  "Brutal Fury":"Spear",
  "Brutal Incision":"Dagger",
  "Brutaler Einschnitt":"Dagger",
  "Brutaler Pfeil":"Longbow",
  "Brutaler Zorn":"Spear",
  "Burning Smokescreen":"Staff",
  "Camouflage Cloak":"Dagger",
  "Cataclysm":"Spear",
  "Chain Hook":"Sword and Shield",
  "Chain Lightning":"Staff",
  "Chain Strike":"Gauntlet",
  "Chaos stiften":"Spear",
  "Chaosschild":"Wand and Tome",
  "Chaotic Shield":"Wand and Tome",
  "Charging Slash":"Greatsword",
  "Clay's Salvation":"Wand and Tome",
  "Clays Erl\u00f6sung":"Wand and Tome",
  "Cleaving Moonlight":"Dagger",
  "Cold Warrior":"Greatsword",
  "Collision Shot":"Crossbow",
  "Concentrated Barrier":"Sword and Shield",
  "Concentration Stance":"Longbow",
  "Constellation Link":"Orb",
  "Constricting Tempest":"Spear",
  "Controlling Rake":"Sword and Shield",
  "Corrupt Nail":"Crossbow",
  "Corrupted Magic Circle":"Wand and Tome",
  "Counter Barrier":"Sword and Shield",
  "Cradle of Stars":"Orb",
  "Culling Arc":"Spear",
  "Curse Explosion":"Wand and Tome",
  "Curse Resonance":"Wand and Tome",
  "Cursed Nightmare":"Wand and Tome",
  "Cyclonic Fury":"Spear",
  "DaVinci's Chill":"Greatsword",
  "DaVinci's Courage":"Greatsword",
  "DaVincis K\u00fchle":"Greatsword",
  "Deadly Marker":"Longbow",
  "Death Blow":"Greatsword",
  "Death From Above":"Spear",
  "Death Knell":"Spear",
  "Decaying Touch":"Wand and Tome",
  "Decisive Bombardment":"Longbow",
  "Decisive Sniping":"Longbow",
  "Desperate Clash":"Sword and Shield",
  "Destructive Fang":"Dagger",
  "Detect Vulnerability":"Dagger",
  "Detection":"Crossbow",
  "Detonation Mark":"Crossbow",
  "Detonierendes Mal":"Crossbow",
  "Devastating Smash":"Greatsword",
  "Devastating Tornado":"Greatsword",
  "Devoted Sanctuary":"Greatsword",
  "Devoted Shield":"Longbow",
  "Devotion and Emptiness":"Wand and Tome",
  "Distorted Sanctuary":"Longbow",
  "Distortion Veil":"Orb",
  "Donnernde Bombe":"Dagger",
  "Durchbohrender Schlag":"Crossbow",
  "Durchbruch":"Gauntlet",
  "Dynamik":"Gauntlet",
  "Eagle Vision":"Crossbow",
  "Earth's Blessing":"Longbow",
  "Earthquake":"Gauntlet",
  "Echobarriere":"Staff",
  "Echoes of Distortion":"Orb",
  "Echoic Barrier":"Staff",
  "Echos der Verzerrung":"Orb",
  "Eclipse of Blood":"Gauntlet",
  "Edle Belebung":"Wand and Tome",
  "Eid des Heiligen":"Wand and Tome",
  "Ein-Zoll-Schlag":"Gauntlet",
  "Eine Chance auf den Sieg":"Sword and Shield",
  "Einengender Sturm":"Spear",
  "Eisenparieren":"Greatsword",
  "Eisgebundene R\u00fcstung":"Staff",
  "Eisgebundenes Grab":"Staff",
  "Eisspeer":"Staff",
  "Eisspeer-Bombardement":"Staff",
  "Eistornado":"Greatsword",
  "Elemental Awakening":"Staff",
  "Elementarerweckung":"Staff",
  "Enchanting Time":"Wand and Tome",
  "Enforcer":"Spear",
  "Ensnaring Arrow":"Longbow",
  "Entschlossener Scharfschuss":"Longbow",
  "Entschlossenes Bombardement":"Longbow",
  "Erdbeben":"Gauntlet",
  "Erfassung":"Crossbow",
  "Ergebener Schild":"Longbow",
  "Erl\u00f6sende Barriere":"Staff",
  "Erl\u00f6sungskette":"Staff",
  "Eternal Veil":"Orb",
  "Ewiger Schleier":"Orb",
  "Explosive Flurry":"Gauntlet",
  "Explosive Fury":"Spear",
  "Explosive Trap":"Crossbow",
  "Explosiver Wirbel":"Gauntlet",
  "Explosiver Zorn":"Spear",
  "Eye of Ventius":"Longbow",
  "Fallbeilklinge":"Greatsword",
  "Fatal Precision":"Spear",
  "Fatal Stigma":"Dagger",
  "Fegen":"Gauntlet",
  "Fesselnder Pfeil":"Longbow",
  "Feuerballsperrfeuer":"Staff",
  "Fierce Clash":"Sword and Shield",
  "Fireball Barrage":"Staff",
  "Flame Condensation":"Staff",
  "Flammenverdichtung":"Staff",
  "Flash Arrow":"Longbow",
  "Flash Wave":"Longbow",
  "Flinke Schritte":"Spear",
  "Flinker Sprung":"Crossbow",
  "Fluchexplosion":"Wand and Tome",
  "Fluchresonanz":"Wand and Tome",
  "Focused Fire Bombs":"Staff",
  "Fokussierte Feuerbomben":"Staff",
  "Forbidden Sanctuary":"Staff",
  "Fortifying Shell":"Gauntlet",
  "Fountain of Life":"Wand and Tome",
  "Frenzied Lightning Wave":"Staff",
  "Frenzied Sword Dance":"Dagger",
  "Frost Cleaving":"Greatsword",
  "Frost Master":"Staff",
  "Frost Smokescreen":"Staff",
  "Frostmeister":"Staff",
  "Frostnebelschleier":"Staff",
  "Full of Corruption":"Wand and Tome",
  "Gaia Crash":"Greatsword",
  "Gaiasturz":"Greatsword",
  "Gale Rush":"Spear",
  "Geduldiger Block":"Spear",
  "Geist des Donners":"Dagger",
  "Gerad's Patience":"Sword and Shield",
  "Gerad's Shield":"Sword and Shield",
  "Gerads Geduld":"Sword and Shield",
  "Gerechte Wut":"Sword and Shield",
  "Geschicktes Ausweichen":"Sword and Shield",
  "Gesegnete Barriere":"Wand and Tome",
  "Gewitterschlag":"Spear",
  "Giftspritze":"Dagger",
  "Gnadenloses Sperrfeuer":"Crossbow",
  "Grausamer Zorn":"Spear",
  "Gravity Star Destroyer":"Orb",
  "Grenz\u00fcberwindung":"Longbow",
  "Guardian Defensive Wall":"Orb",
  "Guillotine Blade":"Greatsword",
  "Hardening":"Gauntlet",
  "Hauch der Verzweiflung":"Wand and Tome",
  "Healing Star":"Orb",
  "Healing Touch":"Longbow",
  "Healing Wave":"Orb",
  "Heftiger Zusammensto\u00df":"Sword and Shield",
  "Heilende Ber\u00fchrung":"Longbow",
  "Heilender Stern":"Orb",
  "Hellfire Rain":"Staff",
  "Hieb der Leere":"Orb",
  "High Focus":"Staff",
  "Hingebungsvolle Zuflucht":"Greatsword",
  "Hoher Fokus":"Staff",
  "H\u00f6llenfeuerregen":"Staff",
  "H\u00f6llischer Meteor":"Staff",
  "Ice Spear":"Staff",
  "Ice Spear Bombardment":"Staff",
  "Ice Tornado":"Greatsword",
  "Icebound Armor":"Staff",
  "Icebound Tomb":"Staff",
  "Immortal Pride":"Sword and Shield",
  "Impenetrable":"Sword and Shield",
  "Imposing Form":"Spear",
  "Incapacitate":"Gauntlet",
  "Indomitable Armor":"Greatsword",
  "Infernal Meteor":"Staff",
  "Inferno Wave":"Staff",
  "Infernowelle":"Staff",
  "Inject Venom":"Dagger",
  "Inner Peace":"Staff",
  "Innerer Frieden":"Staff",
  "Instinkt des Assassinen":"Dagger",
  "Interstellar Explosion":"Orb",
  "Interstellare Explosion":"Orb",
  "Invincible Wall":"Wand and Tome",
  "Iron Point Parry":"Greatsword",
  "Janice's Rage":"Wand and Tome",
  "Janice\u2019 Wut":"Wand and Tome",
  "Javelin Inferno":"Spear",
  "Javelin Surge":"Spear",
  "Judgment Lightning":"Staff",
  "Jumping Chain":"Staff",
  "Kalter Krieger":"Greatsword",
  "Karmic Haze":"Wand and Tome",
  "Karmischer Hauch":"Wand and Tome",
  "Kettenblitzschlag":"Staff",
  "Kettenhaken":"Sword and Shield",
  "Kettenschlag":"Gauntlet",
  "Klinge blocken":"Dagger",
  "Knife Throwing":"Dagger",
  "Kn\u00f6chelhieb":"Dagger",
  "Kollisionsschuss":"Crossbow",
  "Konstellation beschw\u00f6ren":"Orb",
  "Konstellations-Verbindung":"Orb",
  "Konterbarriere":"Sword and Shield",
  "Konzentrationshaltung":"Longbow",
  "Konzentrierte Barriere":"Sword and Shield",
  "Korrupter Nagel":"Crossbow",
  "K\u00f6rpertraining":"Gauntlet",
  "K\u00fchne Pr\u00fcgel":"Greatsword",
  "Lebensbrunnen":"Wand and Tome",
  "Lenkende Harke":"Sword and Shield",
  "Lightning Infusion":"Dagger",
  "Lightning Throw":"Dagger",
  "Limit Break":"Longbow",
  "Locken des Geistes":"Wand and Tome",
  "Macht der Natur":"Crossbow",
  "Mad Sword Dance":"Dagger",
  "Malice Surge":"Spear",
  "Mana Amp":"Staff",
  "Mana Exchange":"Crossbow",
  "Mana-Austausch":"Crossbow",
  "Manaball Eruption":"Staff",
  "Manasph\u00e4renausbruch":"Staff",
  "Manaverst\u00e4rkung":"Staff",
  "Master of Provocation":"Gauntlet",
  "Meister der Provokation":"Gauntlet",
  "Merciless Barrage":"Crossbow",
  "Messerwerfen":"Dagger",
  "Milchstra\u00dfe":"Orb",
  "Milky Way":"Orb",
  "Mobility Strike":"Gauntlet",
  "Momentum":"Gauntlet",
  "Moral des Siegers":"Greatsword",
  "Morale Boost":"Sword and Shield",
  "Moralschub":"Sword and Shield",
  "Mortal Mark":"Crossbow",
  "Mortal Wrath":"Spear",
  "Mother Nature's Protest":"Crossbow",
  "Multi-Shot":"Crossbow",
  "Multischuss":"Crossbow",
  "Murderous Energy":"Dagger",
  "Mut des DaVinci":"Greatsword",
  "Mystic Shield":"Staff",
  "Mystischer Schild":"Staff",
  "M\u00f6rderische Energie":"Dagger",
  "Nature's Blessing":"Longbow",
  "Nature's Power":"Crossbow",
  "Nimble Leap":"Crossbow",
  "Nimble Steps":"Spear",
  "Noble Revival":"Wand and Tome",
  "One-Inch Punch":"Gauntlet",
  "Overtaker":"Longbow",
  "Patient Block":"Spear",
  "Pfeilwirbel":"Longbow",
  "Phantom Smokescreen":"Dagger",
  "Phantomnebelwand":"Dagger",
  "Phoenix Barrage":"Spear",
  "Physique Training":"Gauntlet",
  "Ph\u00f6nix-Sperrfeuer":"Spear",
  "Piercing Strike":"Crossbow",
  "Precision Dash":"Greatsword",
  "Protest von Mutter Natur":"Crossbow",
  "Provoking Roar":"Sword and Shield",
  "Provozierendes Br\u00fcllen":"Sword and Shield",
  "Pr\u00e4zisionssprint":"Greatsword",
  "Puls der Schlachtfelder":"Spear",
  "Pulsating Galaxy":"Orb",
  "Pulse of the Battlegrounds":"Spear",
  "Pulsierende Galaxie":"Orb",
  "Purifying Touch":"Longbow",
  "Quick Fire":"Crossbow",
  "Raging Frenzy":"Greatsword",
  "Rapid Shot":"Crossbow",
  "Rapidfire Stance":"Longbow",
  "Rasche Heilung":"Wand and Tome",
  "Rasende Blitzwelle":"Staff",
  "Raum\u00fcbergang":"Orb",
  "Ray of Disaster":"Wand and Tome",
  "Recoil Shot":"Crossbow",
  "Redemptive Barrier":"Staff",
  "Reihen-Brandbomben":"Staff",
  "Reinigende Ber\u00fchrung":"Longbow",
  "Resilient Mind":"Sword and Shield",
  "Restoring Constellation":"Orb",
  "Retaliatory Strike":"Spear",
  "Rift Fracture":"Orb",
  "Righteous Fury":"Sword and Shield",
  "Rising Slash":"Spear",
  "Robust Constitution":"Greatsword",
  "Robuste Konstitution":"Greatsword",
  "Roxie's Arrowhead":"Longbow",
  "Roxies Pfeilspitze":"Longbow",
  "Rupturing Parry":"Crossbow",
  "R\u00fccksto\u00df-Schuss":"Crossbow",
  "Saint's Oath":"Wand and Tome",
  "Salvation Chain":"Staff",
  "Satellit beschw\u00f6ren":"Orb",
  "Schattenhafter Geist":"Dagger",
  "Schattenl\u00e4ufer":"Dagger",
  "Schattenstreich":"Dagger",
  "Schild von Gerad":"Sword and Shield",
  "Schildangriff":"Sword and Shield",
  "Schildwurf":"Sword and Shield",
  "Schild\u00fcberlebenstechnik":"Sword and Shield",
  "Schlachtender Bogen":"Spear",
  "Schlachthieb":"Spear",
  "Schmetternder Speer":"Spear",
  "Schneller Schuss":"Crossbow",
  "Schnellfeuer":"Crossbow",
  "Schnellfeuerhaltung":"Longbow",
  "Schwachpunktschuss":"Crossbow",
  "Schwachstelle orten":"Dagger",
  "Schwerkraft-Sternenzerst\u00f6rer":"Orb",
  "Sch\u00fctzender Panzer":"Gauntlet",
  "Segen der Erde":"Longbow",
  "Segen der Natur":"Longbow",
  "Segen der Unsterblichkeit":"Sword and Shield",
  "Selbstlose Seele":"Wand and Tome",
  "Selbstlose Streuung":"Crossbow",
  "Selfless Diffusion":"Crossbow",
  "Selfless Soul":"Wand and Tome",
  "Sentinel's Bastion":"Spear",
  "Serial Fire Bombs":"Staff",
  "Shadow Strike":"Dagger",
  "Shadow Walker":"Dagger",
  "Shield Strike":"Sword and Shield",
  "Shield Survival Technique":"Sword and Shield",
  "Shield Throw":"Sword and Shield",
  "Short Jab":"Gauntlet",
  "Sinn des Scharfsch\u00fctzen":"Longbow",
  "Skillful Evasion":"Sword and Shield",
  "Slaughtering Slash":"Spear",
  "Sniper's Sense":"Longbow",
  "Sonnenfinsternis des Blutes":"Gauntlet",
  "Space Transition":"Orb",
  "Spaltbruch":"Orb",
  "Spaltender Frost":"Greatsword",
  "Spaltendes Mondlicht":"Dagger",
  "Spectrum of Agony":"Sword and Shield",
  "Speerinferno":"Spear",
  "Spektrum der Qual":"Sword and Shield",
  "Sprengfalle":"Crossbow",
  "Springende Kette":"Staff",
  "Sprint des Barbaren":"Greatsword",
  "Stalwart Bastion":"Sword and Shield",
  "Standhafte Bastion":"Sword and Shield",
  "Star Destroyer":"Orb",
  "Starcalling":"Orb",
  "Steady Aim":"Longbow",
  "Stellar Cycle":"Orb",
  "Stellar Dash":"Orb",
  "Stellar Echo":"Orb",
  "Sternenruf":"Orb",
  "Sternenzerst\u00f6rer":"Orb",
  "Storm Current":"Crossbow",
  "Strafing":"Longbow",
  "Strahl des Verderbens":"Wand and Tome",
  "Strategic Rush":"Sword and Shield",
  "Strategischer Ansturm":"Sword and Shield",
  "Stunning Blow":"Greatsword",
  "Sturm-Sprint":"Spear",
  "Sturmstr\u00f6mung":"Crossbow",
  "St\u00fcrmischer Schlag":"Greatsword",
  "St\u00fcrmischer Zorn":"Spear",
  "Summon Constellation":"Orb",
  "Summon Guardian Satellite":"Orb",
  "Summon Satellite":"Orb",
  "Supernova Collapse":"Orb",
  "Supernova-Zusammenbruch":"Orb",
  "Suppressing Strike":"Greatsword",
  "Sweep":"Gauntlet",
  "Swift Healing":"Wand and Tome",
  "Tarnmantel":"Dagger",
  "Taunt":"Gauntlet",
  "Tempest Strike":"Spear",
  "Temporal Leap":"Orb",
  "Threat Boost":"Gauntlet",
  "Thunder Spirit":"Dagger",
  "Thundering Bomb":"Dagger",
  "Time Dilation":"Orb",
  "Time for Punishment":"Wand and Tome",
  "Tobende Raserei":"Greatsword",
  "Tod von oben":"Spear",
  "Todesschlag":"Greatsword",
  "Tornado":"Longbow",
  "Totenglocke":"Spear",
  "Touch of Despair":"Wand and Tome",
  "Trance":"Gauntlet",
  "T\u00f6dliche Markierung":"Longbow",
  "T\u00f6dliche Pr\u00e4zision":"Spear",
  "T\u00f6dlicher Zorn":"Spear",
  "T\u00f6dliches Mal":"Crossbow",
  "T\u00f6dliches Stigma":"Dagger",
  "Umbral Spirit":"Dagger",
  "Unberechenbarkeit":"Gauntlet",
  "Unbeugsamer W\u00e4chter":"Spear",
  "Unbezwingbare R\u00fcstung":"Greatsword",
  "Unbezwingbare Wand":"Wand and Tome",
  "Undurchdringlich":"Sword and Shield",
  "Unersch\u00fctterliche Haltung":"Gauntlet",
  "Unpredictable":"Gauntlet",
  "Unshakable Stance":"Gauntlet",
  "Unsterblicher Stolz":"Sword and Shield",
  "Unterdr\u00fcckender Schlag":"Greatsword",
  "Unyielding Sentinel":"Spear",
  "Urteilsblitz":"Staff",
  "Valiant Brawl":"Greatsword",
  "Vampiric Contract":"Wand and Tome",
  "Vampiric Strike":"Dagger",
  "Vampirischer Vertrag":"Wand and Tome",
  "Vampirschlag":"Dagger",
  "Verbotenes Heiligtum":"Staff",
  "Verdorbener magischer Kreis":"Wand and Tome",
  "Verfluchter Alptraum":"Wand and Tome",
  "Vergeltender Hieb":"Spear",
  "Verheerung":"Spear",
  "Verh\u00e4rtung":"Gauntlet",
  "Vernichtender Schlag":"Greatsword",
  "Verr\u00fcckter Schwerttanz":"Dagger",
  "Verspotten":"Gauntlet",
  "Verst\u00e4rkungsschleier":"Orb",
  "Verw\u00fcstender Tornado":"Greatsword",
  "Verzauberungszeit":"Wand and Tome",
  "Verzerrtes Heiligtum":"Longbow",
  "Verzerrungsschleier":"Orb",
  "Verzweifelter Zusammensto\u00df":"Sword and Shield",
  "Vicious Fury":"Spear",
  "Victor's Morale":"Greatsword",
  "Vital Force":"Greatsword",
  "Vitalkraft":"Greatsword",
  "Void Slash":"Orb",
  "Voller Korruption":"Wand and Tome",
  "Vollstrecker":"Spear",
  "Vorwitzige Retorte":"Sword and Shield",
  "Weak Point Shot":"Crossbow",
  "Welle der Heilung":"Orb",
  "Whirling Shield":"Sword and Shield",
  "Wiederherstellungs-Konstellation":"Orb",
  "Wiege der Sterne":"Orb",
  "Wild Barrage":"Crossbow",
  "Wilder Schwerttanz":"Dagger",
  "Wildes Sperrfeuer":"Crossbow",
  "Willbreaker":"Greatsword",
  "Willensbrecher":"Greatsword",
  "Wind Snatcher":"Crossbow",
  "Winddieb":"Crossbow",
  "Wirbelnder Schild":"Sword and Shield",
  "Witty Retort":"Sword and Shield",
  "Wraith's Beckon":"Wand and Tome",
  "Wrathful Edge":"Dagger",
  "Wreak Havoc":"Spear",
  "W\u00e4chter-Satellit beschw\u00f6ren":"Orb",
  "W\u00e4chter-Verteidigungsmauer":"Orb",
  "W\u00e4chterbastion":"Spear",
  "Zahn der Zerst\u00f6rung":"Dagger",
  "Zeit f\u00fcr Bestrafung":"Wand and Tome",
  "Zeiterweiterung":"Orb",
  "Zeitsprung":"Orb",
  "Zephyr's Nock":"Longbow",
  "Zephyrs Nockpunkt":"Longbow",
  "Zielsicherheit":"Longbow",
  "Zornige Schneide":"Dagger",
  "\u00dcberwinder":"Longbow"
};
